# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TransferFiles.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(747, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblLocal = QtWidgets.QLabel(self.centralwidget)
        self.lblLocal.setObjectName("lblLocal")
        self.verticalLayout.addWidget(self.lblLocal)
        self.txtLocalPath = QtWidgets.QLineEdit(self.centralwidget)
        self.txtLocalPath.setObjectName("txtLocalPath")
        self.verticalLayout.addWidget(self.txtLocalPath)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLocalUp = QtWidgets.QToolButton(self.centralwidget)
        self.btnLocalUp.setObjectName("btnLocalUp")
        self.horizontalLayout.addWidget(self.btnLocalUp)
        self.btnLocalBack = QtWidgets.QToolButton(self.centralwidget)
        self.btnLocalBack.setObjectName("btnLocalBack")
        self.horizontalLayout.addWidget(self.btnLocalBack)
        self.btnLocalForward = QtWidgets.QToolButton(self.centralwidget)
        self.btnLocalForward.setObjectName("btnLocalForward")
        self.horizontalLayout.addWidget(self.btnLocalForward)
        self.btnLocalRefresh = QtWidgets.QToolButton(self.centralwidget)
        self.btnLocalRefresh.setObjectName("btnLocalRefresh")
        self.horizontalLayout.addWidget(self.btnLocalRefresh)
        self.btnLocalNewDir = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/directory.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnLocalNewDir.setIcon(icon)
        self.btnLocalNewDir.setObjectName("btnLocalNewDir")
        self.horizontalLayout.addWidget(self.btnLocalNewDir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lstLocal = QtWidgets.QListWidget(self.centralwidget)
        self.lstLocal.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lstLocal.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.lstLocal.setSelectionRectVisible(True)
        self.lstLocal.setObjectName("lstLocal")
        self.verticalLayout.addWidget(self.lstLocal)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.btnToRemote = QtWidgets.QPushButton(self.centralwidget)
        self.btnToRemote.setObjectName("btnToRemote")
        self.verticalLayout_3.addWidget(self.btnToRemote)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.btnToLocal = QtWidgets.QPushButton(self.centralwidget)
        self.btnToLocal.setObjectName("btnToLocal")
        self.verticalLayout_3.addWidget(self.btnToLocal)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblRemote = QtWidgets.QLabel(self.centralwidget)
        self.lblRemote.setObjectName("lblRemote")
        self.verticalLayout_2.addWidget(self.lblRemote)
        self.txtRemotePath = QtWidgets.QLineEdit(self.centralwidget)
        self.txtRemotePath.setObjectName("txtRemotePath")
        self.verticalLayout_2.addWidget(self.txtRemotePath)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnRemoteUp = QtWidgets.QToolButton(self.centralwidget)
        self.btnRemoteUp.setObjectName("btnRemoteUp")
        self.horizontalLayout_2.addWidget(self.btnRemoteUp)
        self.btnRemoteBack = QtWidgets.QToolButton(self.centralwidget)
        self.btnRemoteBack.setObjectName("btnRemoteBack")
        self.horizontalLayout_2.addWidget(self.btnRemoteBack)
        self.btnRemoteForward = QtWidgets.QToolButton(self.centralwidget)
        self.btnRemoteForward.setObjectName("btnRemoteForward")
        self.horizontalLayout_2.addWidget(self.btnRemoteForward)
        self.btnRemoteRefresh = QtWidgets.QToolButton(self.centralwidget)
        self.btnRemoteRefresh.setObjectName("btnRemoteRefresh")
        self.horizontalLayout_2.addWidget(self.btnRemoteRefresh)
        self.btnRemoteNewDir = QtWidgets.QToolButton(self.centralwidget)
        self.btnRemoteNewDir.setIcon(icon)
        self.btnRemoteNewDir.setObjectName("btnRemoteNewDir")
        self.horizontalLayout_2.addWidget(self.btnRemoteNewDir)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.lstRemote = QtWidgets.QListWidget(self.centralwidget)
        self.lstRemote.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lstRemote.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.lstRemote.setSelectionRectVisible(True)
        self.lstRemote.setObjectName("lstRemote")
        self.verticalLayout_2.addWidget(self.lstRemote)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 747, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ChDC ADB"))
        self.lblLocal.setText(_translate("MainWindow", "Local"))
        self.btnLocalUp.setText(_translate("MainWindow", "Up"))
        self.btnLocalBack.setText(_translate("MainWindow", "Back"))
        self.btnLocalForward.setText(_translate("MainWindow", "Forward"))
        self.btnLocalRefresh.setText(_translate("MainWindow", "Refresh"))
        self.btnLocalNewDir.setText(_translate("MainWindow", "..."))
        self.btnToRemote.setText(_translate("MainWindow", ">>"))
        self.btnToLocal.setText(_translate("MainWindow", "<<"))
        self.lblRemote.setText(_translate("MainWindow", "Remote"))
        self.btnRemoteUp.setText(_translate("MainWindow", "Up"))
        self.btnRemoteBack.setText(_translate("MainWindow", "Back"))
        self.btnRemoteForward.setText(_translate("MainWindow", "Forward"))
        self.btnRemoteRefresh.setText(_translate("MainWindow", "Refresh"))
        self.btnRemoteNewDir.setText(_translate("MainWindow", "..."))

import Resources_rc
